### ISSUE TITLE
Cgitize does not detect private user repositories.

### ISSUE THREAD

**Issue by tale** [egor-tensin/cgitize#4]
Unless I'm severely mistaken, it appears that the user repository pull API only gets the public repositories of a user?

https://github.com/egor-tensin/cgitize/blob/d028f5795e45afb20fdd10d99cf2dac7df7e2e44/cgitize/github.py#L26

`NamedUser#get_repos()` calls the `/users/{user}/repos` endpoint on GitHub's REST API.
According to [REST Documentation](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user) this only fetches public repositories and is intentional design. If this is an unintentional side-effect, a possible solution might be to use the [List repositories for an Authenticated User](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user) endpoint. This takes in the same `github_pat` that is already able to be supplied in `cgitize.toml` and will fetch all private repositories.

I'll see about making a PR once you've replied in order to understand if this is an intentional design decision or an accidental bug, but the quickest fix would probably be to use [`AuthenticatedUser#get_repos()`](https://pygithub.readthedocs.io/en/latest/github_objects/AuthenticatedUser.html#github.AuthenticatedUser.AuthenticatedUser.get_repos) when a GitHub token is passed in instead of `NamedUser`.

**Comment by egor-tensin** [comment]
Somebody else uses this, what?! I'll check it out and fix it quickly, don't worry about it.

**Comment by tale** [comment]
Haha yeah, it's a super useful tool I run in my home as a Docker container.
I also found [this link](https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_user) which might be useful in fixing it!

I love the tool, thank you for making it!

**Comment by egor-tensin** [comment]
Fixed. It's a breaking change in the config, so I tagged it with a new major version 5 (Docker tag `5`). To fetch private repositories, you need to specify `github.username` (along with `github.token`) in the config like so:

```
[github]
token = "TOKEN"
username = "USERNAME"

[github.users.foo]
name = "USERNAME"
```

There's a bit of duplication, since `github.username` and `github.users.foo.name` will often be the same, but it's actually required: I need to check if `foo.name` is the same as the authenticated user's name to call the right method in PyGithub. Plus, it still allows specifying multiple GitHub users, albeit at most one will get authenticated access.

The alternative was to move the `token` setting under `github.users` entries, but that's inconsistent with other providers (Bitbucket & Gitlab) and doesn't play well with organizations. Plus, you can always spin up multiple cgitize containers for different users if you want to.

**Comment by tale** [comment]
Thank you for making such a quick fix!
